version: '3'


services:
  core:
    build:
      context: .
      args:
        - PACKAGE=core
    container_name: core
    env_file: ./.env.docker-compose
    environment:
        #s non secret
      - ASSETS_BUCKET_NAME=assets.byron.pubpub.org
      - MAILGUN_SMTP_HOST=smtp.mailgun.org
      - MAILGUN_SMTP_PORT=465
      - MAILGUN_SMTP_USERNAME=omitted
      - NEXT_PUBLIC_PUBPUB_URL=http://localhost:8080
      - NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
      - OTEL_SERVICE_NAME=core.core
      - PGDATABASE=postgres
      - PGHOST=host.docker.internal
      - PGPORT=54322
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PUBPUB_URL=http://localhost:8080
      - SUPABASE_URL=http://host.docker.internal:54321
    networks:
      - app-network
    ports:
      - "30000:3000"

  core-nginx:
    build: ./infrastructure/nginx
    container_name: core-nginx
    environment:
      - NGINX_LISTEN_PORT=8080
      - NGINX_PREFIX=/
      - NGINX_UPSTREAM_HOST=core
      - NGINX_UPSTREAM_PORT=3000
      - OTEL_SERVICE_NAME=core.nginx
    depends_on:
      - core
    networks:
      - app-network
    ports:
      - "3000:8080"

  jobs:
    build:
      context: .
      args:
        - PACKAGE=jobs
    container_name: jobs
    env_file: ./.env.docker-compose
    environment:
      - OTEL_SERVICE_NAME=jobs.jobs
      - PGDATABASE=postgres
      - PGHOST=host.docker.internal
      - PGPORT=54322
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PUBPUB_URL=http://localhost:8080
    networks:
      - app-network

  # jobs-nginx:
  # No Nginx for jobs, because it does not take requests

  integration-submissions:
    build:
      context: .
      args:
        - PACKAGE=integration-submissions
    container_name: integration-submissions
    env_file: ./.env.docker-compose
    environment:
      - SENTRY_AUTH_TOKEN=omitted

      - OTEL_SERVICE_NAME=integration-submissions.integration-submissions
      - PUBPUB_URL=http://localhost:8080
    depends_on:
      - core
    networks:
      - app-network
    ports:
      - "30001:3000"

  integration-submissions-nginx:
    build: ./infrastructure/nginx
    container_name: integration-submissions-nginx
    environment:
      - NGINX_LISTEN_PORT=8080
      - NGINX_PREFIX=/intg/submissions/
      - NGINX_UPSTREAM_HOST=integration-submissions
      - NGINX_UPSTREAM_PORT=3000
      - OTEL_SERVICE_NAME=integration-submissions.nginx
    depends_on:
      - integration-submissions
    networks:
      - app-network
    ports:
      - "3001:8080"

  integration-evaluations:
    build:
      context: .
      args:
        - PACKAGE=integration-evaluations
    container_name: integration-evaluations
    env_file: ./.env.docker-compose
    environment:
      - SENTRY_AUTH_TOKEN=omitted

      - OTEL_SERVICE_NAME=integration-evaluations.integration-evaluations
      - PUBPUB_URL=http://localhost:8080
    depends_on:
      - core
    networks:
      - app-network
    ports:
      - "30002:3000"

  integration-evaluations-nginx:
    build: ./infrastructure/nginx
    container_name: integration-evaluations-nginx
    environment:
      - NGINX_LISTEN_PORT=8080
      - NGINX_PREFIX=/intg/evaluations/
      - NGINX_UPSTREAM_HOST=integration-evaluations
      - NGINX_UPSTREAM_PORT=3000
      - OTEL_SERVICE_NAME=integration-evaluations.nginx
    depends_on:
      - integration-evaluations
    networks:
      - app-network
    ports:
      - "3002:8080"

  # postgres:
  #   image: postgres:15
  #   container_name: postgres
  #   environment:
  #     - POSTGRES_USER=byron
  #     - POSTGRES_PASSWORD=byron
  #     - POSTGRES_DB=byron_test_core_postgres
  #   volumes:
  #     - byron-postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - app-network
  #   ports:
  #     - "54320:5432"

# volumes:
  # byron-postgres-data:

networks:
  app-network:
