services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile.test
            args:
                - PACKAGE=core
        image: core
        env_file:
            - core/.env.testing
        restart: unless-stopped
        depends_on:
            - postgres
        ports:
            - 3000:3000
    postgres:
        image: postgres:15.1
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
    # dbeaver:
    #     image: dbeaver/cloudbeaver
    #     restart: always
    #     ports:
    #     - '5051:8978'