version: "3"

services:
    app:
        build:
            context: .
            args:
                - PACKAGE=core
        image: core
        env_file:
            - core/.env.development

        restart: unless-stopped

    # db:
    #     image: postgres:15.1
    #     restart: unless-stopped
    #     environment:
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: postgres
    #         POSTGRES_DB: postgres
