services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile.test
            args:
                - PACKAGE=core
        image: core
        env_file:
            - core/.env.testing
        restart: unless-stopped
        depends_on:
            - postgres
        ports:
            - 8000:8000
    postgres:
        image: postgres:15.1
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - postgres