previewsEnabled: false
services:
    # integration-submissions
    - type: web
      name: integration-submissions
      env: docker
      rootDir: ./integrations/submissions-proxy
      dockerfilePath: ./Dockerfile
    # integration-evaluations
    - type: web
      name: integration-evaluations
      env: docker
      rootDir: ./integrations/evaluations-proxy
      dockerfilePath: ./Dockerfile
