previewsEnabled: true
services:
- type: web
  name: core
  runtime: node
  rootDir: .
  buildCommand: pnpm install; pnpm build --filter core...
  startCommand: pnpm start --filter core
  envVars:
    - fromGroup: pubpub-core-prod-env