name: "CI"
on:
    workflow_call:
    workflow_dispatch:

env:
    CI: true

jobs:
    ci:
        timeout-minutes: 15
        runs-on: ubuntu-latest
        env:
            COMPOSE_FILE: docker-compose.test.yml
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build docker image
              run: docker compose --profile test build

            - name: Run migrations
              run: docker compose run core pnpm --filter core migrate-test

            - name: Run prettier
              run: docker compose run core pnpm format

            - name: Run eslint
              run: docker compose run core pnpm lint

            - name: Run typecheck
              run: docker compose run core pnpm type-check

            - name: Run vitest tests
              run: docker compose run core
