# Based on https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service

name: PR Updated triggers

on:
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    ci:
        uses: ./.github/workflows/ci.yml
    build-all:
        uses: ./.github/workflows/ecrbuild-all.yml
        secrets:
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
